GET http://localhost:8080/api/groceries/

###

GET http://localhost:8080/api/favourites

###
POST http://localhost:8080/api/favourites/
Content-Type: application/json

 {
    "name": "Eggs",
    "price": 2.99,
    "quantity": "12 count",
    "category": "Dairy"
 }

###
POST http://localhost:8080/api/groceries/
Content-Type: application/json

 {
    "name": "Eggs",
    "price": 2.99,
    "quantity": "12 count",
    "category": "Dairy",
    "createdAt": 
 }

###
DELETE http://localhost:8080/api/favourites/64107136fb7251455bd07a82

###
PATCH http://localhost:8080/api/gorceries/:id
Content-Type:  application/json

{
  "name": "Paprika"
}